const fs = require("fs");
const paths = [
  "src",
  "src/components",
  "src/hooks",
  "src/services",
  "src/styles",
  "src/utils",
  "public",
  "public/icons",
  "tailwind.config.js",
  "postcss.config.js"
];

paths.forEach((p) => {
  if (!fs.existsSync(p)) {
    if (p.endsWith(".js")) {
      fs.writeFileSync(p, "// Auto-generated by verify-setup.js\n");
      console.log(`🧩 Archivo creado: ${p}`);
    } else {
      fs.mkdirSync(p, { recursive: true });
      console.log(`📁 Carpeta creada: ${p}`);
    }
  } else {
    console.log(`✅ Ya existe: ${p}`);
  }
});
